set_property PACKAGE_PIN R2 [get_ports X]
set_property PACKAGE_PIN T1 [get_ports Y]
set_property PACKAGE_PIN L1 [get_ports Z]
set_property IOSTANDARD LVCMOS33 [get_ports X]
set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports Z]
