wandb_version: 1

architecture:
  desc: null
  value: feedforward
lr:
  desc: null
  value: 0.01
hidden_size:
  desc: null
  value: 200
scheduler_factor:
  desc: null
  value: 0.2
scheduler_patience:
  desc: null
  value: 2
scheduler_min_lr:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710616147.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
