networks:
  mynet:

volumes:
  grafana-vol:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - mynet
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - mynet
    ports:
      - 3000:3000
    volumes:
      - grafana-vol:/var/lib/grafana