global:
  scrape_interval: 15s
scrape_configs:
- job_name: node
  static_configs:
   - targets: ['raspberrypi.local:9100']
- job_name: apache-scraper
  static_configs:
   - targets: ['raspberrypi.local:9117']